"""
Unicode names
"""
__author__ = "Pierre Nugues"

print("\N{LATIN CAPITAL LIGATURE OE}", "\N{LATIN CAPITAL LETTER O WITH DIAERESIS}",
      "\N{LATIN SMALL LETTER O WITH DIAERESIS}", "\u0152", "\u00D6", " \77", "\x40")
print("\N{LATIN CAPITAL LIGATURE OE}")
print("\N{LATIN SMALL LETTER O WITH DIAERESIS}")
print("\N{LATIN CAPITAL LIGATURE OE}, \N{LATIN SMALL LETTER O WITH DIAERESIS}")
print("\N{LATIN SMALL LETTER O WITH DIAERESIS}")
